services:
  - type: web
    name: smart-tech-lab
    runtime: node
    plan: free
    buildCommand: npm install --prefix src && npm install --prefix Frontend/frontend && npm run build --prefix Frontend/frontend
    startCommand: node src/index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: DB_CONNECT_STRING
        sync: false
      - key: JWT_KEY
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASS
        sync: false
      - key: REDIS_USER
        value: default
      - key: REDIS_TLS
        value: "true"
      - key: GEMINI_API_KEY
        sync: false
      - key: MAIL_SERVICE
        value: gmail
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: SMTP_FROM_NAME
        value: Smart Tech Lab
      - key: GOOGLE_CLIENT_ID
        sync: false
